### ISSUE TITLE
函数看不懂😂

### ISSUE THREAD

**Issue by peter1124** [Rarafell/BaseConverter#1]
看了您的代码，有一下的疑惑🤔，简而言之，您的代码没有注释很难看懂😂，对于我这个菜鸟而言。希望您的适当加一点代码，感谢。劳驾。

void Input(int *originalBase, int *targetBase, int *number, int *numberLength, bool *isNegative)//输入函数中有一部分看不懂，如下；
 if (temp[i] == '-')
            {
                *isNegative = true;
                i++;
                offset++;
            }
            if (temp[i] == '0')
            {
                i++;
                offset++;
                if (temp[i] == 'x' || temp[i] == 'X')
                {
                    i++;
                    offset++;
                }
            }
            for (; temp[i] != '\0'; i++)
            {
                if (temp[i] >= '0' && temp[i] <= '9')
                {
                    number[i - offset] = temp[i] - ('0' - 0);
                }
                else if (temp[i] >= 'A' && temp[i] <= 'F')
                {
                    number[i - offset] = temp[i] - ('A' - 10);
                }
                else if (temp[i] >= 'a' && temp[i] <= 'f')
                {
                    number[i - offset] = temp[i] - ('a' - 10);
                }
  long long ConvertToDecimal(const int originalBase, int *number, const int numberLength)//这个函数也有一段代码不明白；
temporaryDecimalNumber += number[i] * pow(originalBase, numberLength - (i + 1));
//这个为什么要用pow（）函数；C 库函数 double pow(double x, double y) 返回 x 的 y 次幂，即 xy。
void ConvertToTargetBase(const long long temporaryDecimalNumber, const int targetBase, int *result, int *resultLength)//这个函数memset（）也不太懂。
  memset(result, 0, sizeof(result));

C 库函数 void *memset(void *str, int c, size_t n) 复制字符 c（一个无符号字符）到参数 str 所指向的字符串的前 n 个字符。

**Comment by Rarafell** [comment]
在你问的这些地方写了注释，还有什么疑问的话继续给我发邮件就好
当时写这个的时候主要是练习用，其实没想过有人能看到的，所以一点注释都没写哈哈哈哈哈哈
[BaseConverter.zip](https://github.com/Rarafell/BaseConverter/files/4420153/BaseConverter.zip)
